#cloud-config
users:
  - name: airbyte
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKGIoSX0JmICb6Q30zeitvnrPk3To57tc0xtHzPFEM3tmzVCyoiLpXHqKv7+eQbM3QOf8Ikp6kHqEC2YSNG1KRNmtOFZNKnZBrnsauhiwkQaijRjhkjhguClKULL9oSU5+h84pDxEZFwS+H7RDXcaa4EidNN8f4VJHMnQOM47nusaJNbhrrzXfvn8ye/Dr6RjHJzchSZjZW4dcAfKkog3TIuDARkJcpzUV7yOmu7ZHxMK/Y0DzZXy+VKi9jm5+NgArSZvF3imz4ENe0CRHJfG2/rrplfQ2jgdOBuP8iXWOmShqpYAFxfkjPhjuFLokGUrd4992fxoZrF1mkHvpPvBkdIo+7te0UXagDAAUlOzqc1vDqTYLjNmXJXabvLv0lC6NHqQYsJyq8TRKj2z8EtVfpWc6bODX/rr5Os6NKEiXZ2wcrw8FSUtuFXBY+m9alAof8BxUHAsj2MTFo9nAB5pyY6tcKfYERiNEjebp8/zv41gck4F5H6eguilYksa6tTE= smsagaydachnaya@sc-mac-00880
      
